- name: Build a cluster with HA control plane
  hosts: k3s_cluster
  vars_files:
    - variables.yaml
  roles:
    - role: common
    - role: k3s.orchestration.prereq
    - role: k3s.orchestration.k3s_server
