- name: Restart raspberrypi_exporter.timer
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: raspberrypi_exporter.timer
  become: true

- name: Install conntrack package
  ansible.builtin.apt:
    name: conntrack
    state: present
    update_cache: yes
  become: true
